# Generated by Django 3.1.1 on 2020-09-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient_quantity',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='recipes.ingredient', verbose_name='Ингридиент'),
            preserve_default=False,
        ),
    ]
