# Generated by Django 3.1.1 on 2020-09-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200902_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparing_time',
        ),
    ]
