# Generated by Django 3.1.1 on 2020-09-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_preparing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=15, verbose_name='Единицы измерения'),
        ),
    ]
