# Generated by Django 3.1.1 on 2020-09-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20200902_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient_quantity',
            options={'verbose_name': 'Ингридиент для рецепты', 'verbose_name_plural': 'Ингридиенты для рецепта'},
        ),
        migrations.RemoveField(
            model_name='ingredient_quantity',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='recipes.Ingredient_quantity'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Слаг'),
        ),
    ]
