# Generated by Django 3.1.1 on 2020-09-02 11:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20200902_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='recipes.Ingredient_quantity', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин')], max_length=22, verbose_name='Тег'),
        ),
    ]
